// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using my_gatherer_api.Data;

namespace mygathererapi.Migrations
{
    [DbContext(typeof(MyGathererApiDbContext))]
    [Migration("20180711102112_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("my_gatherer_api.Data.Models.Card", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("Id");

                    b.Property<int>("Quantity");

                    b.HasKey("UserId", "Id");

                    b.ToTable("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
