// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using my_gatherer_api.Data;

namespace mygathererapi.Migrations
{
    [DbContext(typeof(MyGathererApiDbContext))]
    [Migration("20180717130024_InventoryItems")]
    partial class InventoryItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("my_gatherer_api.Data.Models.CardItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageUrl");

                    b.Property<string>("ManaCost");

                    b.Property<string>("Name");

                    b.Property<string>("SetName");

                    b.HasKey("Id");

                    b.ToTable("CardItems");
                });

            modelBuilder.Entity("my_gatherer_api.Data.Models.InventoryItem", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("Id");

                    b.Property<int>("Quantity");

                    b.HasKey("UserId", "Id");

                    b.HasIndex("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("my_gatherer_api.Data.Models.InventoryItem", b =>
                {
                    b.HasOne("my_gatherer_api.Data.Models.CardItem", "CardItem")
                        .WithMany("InventoryItems")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
